### ISSUE TITLE
Unexpected behavior in RGB32

### ISSUE THREAD

**Issue by FranceBB** [pinterf/RemoveGrainHD#1]
Hi there, Ferenc,
it's FranceBB here, I couldn't find the Doom9 discussion, so I'll just report it here.
There's an unexpected behavior in RGB32 which you can reproduce with ColorBars:

```
ColorBars(848, 480, pixel_type="RGB32")

RemoveGrainHD()
```

![New File000000](https://user-images.githubusercontent.com/18946343/110340578-5697d800-8021-11eb-94d6-aefdd59c8a33.png)

If however we add a ConverttoRGB24() in the middle and we feed an RGB24 clip to it, it works fine:

```
ColorBars(848, 480, pixel_type="RGB32")
ConverttoRGB24()
RemoveGrainHD()
```

![New File0000001](https://user-images.githubusercontent.com/18946343/110340888-ab3b5300-8021-11eb-9d5e-066566276a60.png)

Everything works fine in yv12, YUY2, yv16, yv24, by the way.

Additional Info: Tested x86 version on XP x86 with an SSE4.2 capable CPU and Avisynth 3.7 x86.

Cheers,
Frank

**Comment by pinterf** [comment]
Excepted behaviour*.
"the variable "planar" must be set to 'true', if the input clip is a planar-in-YUY2 or a planar-in-packed RGB clip. [...] like all other filters of the RemoveGrainHD cannot handle ordinary, non-planar YUY2 and RGB clips and the variable "planar" should prevent the user from accidentialy applying these filters to non-planar YUY2 or RGB clips. The SSETools plugin provided tools to convert non-planar YUY2 and RGB clips on to planar ones and reversely. "

*True, that not setting planar=true for RGB24/32 should have thrown an error but it didn't.

This old "planar" RGB concept - which is done by the above mentioned SSETools - reordered the pixels in each line from the RGBARGBARGBARGBA.... packed order to
RRRRRRRRRRRRGGGGGGGGGGGBBBBBBBBBBB - grouping the color planes together within a line.

**Comment by pinterf** [comment]
The same applies for YUY2, which comes evident when you want to set different parameters for U and V planes.

**Comment by FranceBB** [comment]
Got it, so with planar=false by deafult it shouldn't have been executed in the first place and indeed with:

RemoveGrainHD(planar=true)

the output is correct. Thanks for clarifying. ;)
